language: c
sudo: false

# NOTE: travis won't let us expand variables in the addons section ):
matrix:
  include:
    - compiler: "GHC 7.8.4"
      env:
        GHC=7.8.4
        CABAL=1.18
        URL_ACCELERATE=https://github.com/AccelerateHS/accelerate.git
        SHA_ACCELERATE=15aedff344232893c89e513c1caf4bcf699a2b86
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - cabal-install-1.18
            - ghc-7.8.4

    - compiler: "GHC 7.10.2"
      env:
        GHC=7.10.2
        CABAL=1.22
        URL_ACCELERATE=https://github.com/AccelerateHS/accelerate.git
        SHA_ACCELERATE=15aedff344232893c89e513c1caf4bcf699a2b86
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - cabal-install-1.22
            - ghc-7.10.2

cache:
  directories:
    - $HOME/.cabal-snapshot

before_install:
    - unset CC
    - export PATH=/opt/cabal/${CABAL}/bin:${PATH}       # hvr-installed cabal
    - export PATH=/opt/ghc/${GHC}/bin:${PATH}           # hvr-installed ghc

install:
    - cabal update
    - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config

    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
    - cabal --version

    - .travis/install_dependencies.sh

script:
    # Check the build
    - cabal configure -v2 -flib-Werror ${MODE}
    - cabal build
    - cabal haddock
#    - cabal test --show-details=always

    # Check the source distribution can be generated, built, and installed
    - cabal sdist
    - |
        export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}')
        cd dist
        if [ -f "$SRC_TGZ" ]; then
            cabal install --force-reinstalls ${MODE} ${SRC_TGZ} || exit 1
        else
            echo "'$SRC_TGZ': not found"
            exit 1
        fi


after_failure:
    - dmesg

