# vim: nospell
language: minimal
sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: GHC=7.8.4 CABAL=1.18
      compiler: "GHC 7.8"
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.8.4
            - cabal-install-1.18
            - happy-1.19.5
            - alex-3.1.4

    - env: GHC=7.10.2 CABAL=1.22
      compiler: "GHC 7.10"
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.2
            - cabal-install-1.22
            - happy-1.19.5
            - alex-3.1.4

  allow_failures:
    - env: GHC=8.0.1 CABAL=1.24

before_install:
  - export PATH=/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH

  # Fetch stack
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://www.stackage.org/stack/linux-x86_64" | gunzip | tar -x
  - mv stack-*/stack $HOME/bin
  - ln -s stack-${GHC%.*}.yaml stack.yaml
  - travis_retry stack setup
  - travis_retry stack install hscolour

install:
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - travis_retry stack build --only-dependencies --no-terminal --no-haddock-deps -j2

script:
  - stack build --no-terminal --haddock --no-haddock-deps

notifications:
  slack:
    rooms:
      secure: "ejKPZMm9c/6G2LqzWCNY0Oezl0OZXpeOQYLJicpizoKKQl3MpWnHTro28E9I4QolnpsXSSWatiHffHv24WpkNwfNpfgHl065ZNW//c30hu6zxmQjS5LmJo/aQfz5chRoreZxeZJ1WhH9VhEiKPqVw6R13Qr8ppGFX5LJMPCBz9RsW6woBy5BHfm/0V1eX9QgzFd8U/iV8mE01fCRG00IELWmokyNAsP2Cr3u8i29vaTCDvARUKx4e5bV/feO48TzGSN7aGsAsMFRvj2nDdvzlWGyIwpMseYGoWYzsCBd+IC5IQWsA6UPL93UuYZFHL3IAm8wJafbkJcQQ1P7L00OZFa44xjOsMyD6BW+5sSTe6OWFW/RsFf0/ZBtKjfRmwOaFZFGGLZeva4TCNMl4mOBzpFiux9TNhkaRvnW+q5ICeuxV9dRTpqHLX3YHXgI8ftu8y60Llf6rddPK8TqVvsH1WCsLAnBv0Fb9Xw3KxzG5ZQy2hCsAZJp3+7nIzYrW9p3+VZYVFF14KwDsQLms0n9hEDWVlc1tVXAjjCCtAzaXw7k3ppBP3DhOpXdoevDWn6TNkK9ynLx/SMBOoqd69JymrW69KtZG6/puhmXseQhhgH5MnyMQYF78duYkfFqVpHmGydPYbSqga2GYtHA9u8NZTranqKlf9h27ZFk0YoTpMw="

